[package]
name = "rust-parser"
version = "1.0.0"
authors = ["Miguel Molina <hi@mvader.me>"]

[dependencies]

[lib]
name = "rustparse"
path = "src/lib/lib.rs"

[[bin]]
name = "rust-parser"
path = "src/main.rs"
